// Generated by CoffeeScript 1.6.2
var SlowBrunch,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

module.exports = SlowBrunch = (function() {
  SlowBrunch.prototype.brunchPlugin = true;

  function SlowBrunch(config) {
    this.config = config;
    this.onCompile = __bind(this.onCompile, this);
  }

  SlowBrunch.prototype.onCompile = function(generatedFiles) {
    return console.log("about to be slow!", new Date());
  };

  return SlowBrunch;

})();
