// Generated by CoffeeScript 1.6.2
var AfterBrunch,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

module.exports = AfterBrunch = (function() {
  AfterBrunch.prototype.brunchPlugin = true;

  function AfterBrunch(config) {
    this.config = config;
    this.onCompile = __bind(this.onCompile, this);
  }

  AfterBrunch.prototype.onCompile = function(generatedFiles) {
    return console.log("about to be slow!", new Date());
  };

  return AfterBrunch;

})();
